# Server config
server:
  read_timeout: 4s
  write_timeout: 10s
  max_header_bytes: 1048576 # 1 MB
  time_for_graceful_shutdown: 10s # seconds

# Logger config
logger:
  level: info
  format: json
  output: stdout
  files:
    - filepath

# API information
info:
  service: Golang API sample
  version: 1.0.0
  description: It is the sample of API for Golang
  api_docs_path: /swagger/index.html
